### ISSUE TITLE
Go to Definition for require() functions does not work

### ISSUE THREAD

**Issue by obrejla** [anacierdem/vscode-requirejs#3]
Hi,

these 2 exapmples are not recognized properly:
sync
```
require('pages.dt/js/api/Pages').foo();
```
and async
```
require(['pages.dt/js/api/Pages'], function(pages) {});
```

Thanks.

**Comment by anacierdem** [comment]
Thank you for providing examples, I'll investigate this.

**Comment by anacierdem** [comment]
Committed 05f04782915da334a13ed587b3568920a2e5725d. Both approaches should work now except for multiline statements (#4)

**Comment by anacierdem** [comment]
Could you please confirm?

**Comment by obrejla** [comment]
This does not work...no error in console, just popup "No definition found for 'Pages'".

**Comment by anacierdem** [comment]
Should work with version 0.0.20.

**Comment by obrejla** [comment]
Sorry, it still does not work. "No definition found for 'Pages'".

**Comment by obrejla** [comment]
Could be the problem, that neither `new Pages` nor just `Pages` is returned from the file? We return something different (variables, of results of method calls, etc).

**Comment by anacierdem** [comment]
Returned value is not important. How do you "require" that module? that is the important part.

**Comment by anacierdem** [comment]
If you save the above file in your module path as "module.js" and import the above file by;

    define([
        'module'
    ], function (localUtil) {
        //Can access returned instance
    });

**Comment by obrejla** [comment]
It's required like any other module. But the difference is, that modules, where it does not work have a different parameter name in require callback then the filename they require...
1) ctrl+click does not work (but should, it's valid usage)
```
define([
    'foo/Bar'
], function (bar) { // small case "b" at the beginning...ctrl+click does not work
});
```
2) ctrl+click does not work either (but should, it's still valid usage)
```
define([
    'foo/Bar'
], function (BarImpl) { // "Impl" suffix...ctrl+click does not work
});
```
3) this only works
```
define([
    'foo/Bar'
], function (Bar) { // exact match
});
```

**Comment by anacierdem** [comment]
All three works for me on version 0.0.20. Where exactly are you ctrl clicking?

**Comment by anacierdem** [comment]
Oh, you are clicking module name, I guess..

**Comment by anacierdem** [comment]
Opened #8. I'll close this to clean up if its ok?

**Comment by obrejla** [comment]
Sure.
